# This is a basic workflow to help you get started with Actions

name: push

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-deck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Deck
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.8.0"
      - name: Checkout
        uses: action/checkout@v2
          
      # Runs a single command using the runners shell
      - name: Run Deck 
        run: deck sync --kong-addr http://IP:8001

     
